import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'he' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  he: {
    'about.cta.invite': 'תיאום פגישה למדידה',
    'gallery.view': 'לצפייה',
    'about.process.desc': 'הדרך שלכם למטבח המושלם מתחילה כאן. אנו מנתחים את החלל שלכם, מתחשבים בהרגלים של כל בני המשפחה והופכים משימות טכניות מורכבות לפתרונות אלגנטיים. ב-Elite Design אנו לא רק מייצרים רהיטים – אנו יוצרים את הנוחות שתרגישו בכל יום.',
    'about.years.suffix': '+ שנים',
    'about.philosophy': 'אנחנו לא רק מתקינים ארונות, אנחנו מעצבים את הארגונומיה של החיים שלכם',
    'seo.title': 'Elite Design | מטבחים, ארונות ונגרות בהתאמה אישית - 20 שנות ניסיון',
    'seo.description': 'נגריית Elite Design מתמחה בייצור מטבחים ורהיטים מעל 20 שנה. ארונות, חדרי רחצה ופתרונות נגרות לכל הבית במחירים נוחים ובאיכות מעולה. פנו לייעוץ!',
    // Navigation
    'nav.home': 'עמוד הבית',
    'nav.about': 'אודות',
    'nav.kitchens': 'מטבחים',
    'nav.kitchens.modern': 'מטבחים מודרניים',
    'nav.kitchens.country': 'מטבחים כפריים',
    'nav.kitchens.formica': 'מטבחי פורמייקה',
    'nav.kitchens.wood': 'מטבחי עץ מלא',
    'nav.kitchens.nano': 'מטבחי נאנו',
    'nav.kitchens.acrylic': 'מטבחי אקריל',
    'nav.kitchens.styles': 'סגנונות',
    'nav.kitchens.projects': 'פרויקטים',
    'nav.kitchens.preparation': 'הכנה להתקנה',
    'nav.kitchens.quiz': 'התאמת מטבח',
    'nav.projects': 'פרויקטים',
    'nav.promotions': 'מבצעים',
    'nav.installation': 'הכנה להתקנת מטבח',
    'nav.magazine': 'בלוג',
    'nav.showroom': 'אולם תצוגה',
    'nav.contact': 'צרו קשר',
    'nav.quiz': 'התאמת מטבח',

    // Hero
    'hero.title': 'Elite Design',
    'hero.subtitle': 'kitchens & more',
    'hero.tagline': 'Where Design Meets Quality',
    'hero.promo': 'הנחה מיוחדת על כל המטבחים',
    'hero.discount': '20% הנחה',
    'hero.cta.appointment': 'לתיאום פגישה',
    'hero.cta.details': 'השאירו פרטים',
    'hero.cta.calculator': 'חישוב עלות מטבח',
    'hero.cta.main': 'לחשב את הפרויקט שלך',

    // About Section
    'about.title': 'מטבחים מעוצבים ונגרות בהתאמה אישית',
    'about.decorative': 'Where Design Meets Quality',
    'about.description': 'חברת Elite Design היא עסק עם וותק של מעל 20 שנה בתחום הנגרות. לאורך השנים בנינו אלפי מטבחים ורהיטים עבור לקוחות בכל רחבי הארץ. הסוד שלנו פשוט: אנחנו אוהבים את העבודה שלנו. הניסיון שצברנו בשני עשורים מאפשר לנו לתת לכם פתרון לכל תקציב ולכל צורך. אנחנו לא מאמינים ב"שיטת הסרט הנע" – אצלנו כל לקוח מקבל יחס אישי, תכנון מדויק וליווי מלא עד שהרהיט מותקן בבית.',
    'about.benefits.title': '',
    'about.benefits.1.title': 'גישה אישית',

    'about.benefits.1.desc': 'אנו יוצרים פרויקטים שמתאימים באופן מושלם לחלל שלכם ולקצב החיים שלכם.',

    'about.benefits.2.title': 'חומרי העתיד',

    'about.benefits.2.desc': 'עבודה עם ציפויים חדשניים (נאנו), פורמייקה, אקריל ופורניר טבעי.',

    'about.benefits.3.title': 'מחזור מלא',

    'about.benefits.3.desc': 'ממדידה מקצועית ותכנון בתלת-מימד ועד להתקנה ללא פשרות.',

    'about.benefits.4.title': 'איכות ללא פשרות',

    'about.benefits.4.desc': 'שימוש בפרזול של המותגים המובילים בעולם (Blum, Hettich, Grass) לעמידות מירבית.',


    'benefits.title': 'למה לבחור במטבחים של עלית דיזיין?',
    'whyus.title': 'שלבי העבודה שלנו',
    'benefits.custom.title': 'עיצוב מטבחים מותאם אישית',
    'benefits.custom.desc': 'כל פרויקט הוא יצירת אמנות ייחודית המותאמת לצרכים ולאופי שלכם.',
    'benefits.styles.title': 'מגוון סגנונות',
    'benefits.styles.desc': 'מטבחים מודרניים, מטבחים כפריים, מטבחי פולימר ומטבחי נאנו בטכנולוגיה מתקדמת.',
    'benefits.quality.title': 'איכות ללא פשרות',
    'benefits.quality.desc': 'שימוש בפרזול המתקדם בעולם וחומרי גלם עמידים לשנים רבות.',
    'benefits.local.title': 'ייצור מקומי',
    'benefits.local.desc': 'נגרות עילית כחול-לבן עם בקרה קפדנית על כל פרט ופרט.',
    'whyus.decorative': 'working process',
    'process.step1.title': 'סקיצה והערכת מחיר',
    'process.step1.desc': 'אנו נבנה סקיצה ראשונית ונחשב את עלות המטבח עבורכם',
    'process.step2.title': 'מדידה',
    'process.step2.desc': 'המודד המקצועי שלנו יגיע אליכם בזמן שנוח לכם',
    'process.step3.title': 'ייצור',
    'process.step3.desc': 'אנו מייצרים את המטבח במפעל שלנו עם הטכנולוגיה המתקדמת ביותר',
    'process.step4.title': 'הובלה והרכבה',
    'process.step4.desc': 'נוביל את המטבח ונתקין אותו בביתכם בצורה מקצועית',
    'process.step.label': 'שלב',
    'whyus.cta': 'לפרטים נוספים לחץ כאן',

    // Kitchen Categories
    'kitchens.title': 'סגנונות מטבח',
    'kitchens.modern': 'מטבחים מודרניים',
    'kitchens.modern.en': 'Modern kitchens',
    'kitchens.modern.desc': 'מטבחים מודרניים: קווים נקיים, מראה מינימליסטי ופתרונות אחסון חכמים.',
    'kitchens.country': 'מטבחים כפריים',
    'kitchens.country.en': 'Country kitchens',
    'kitchens.country.desc': 'מטבחים כפריים: חמימות של עץ טבעי, עיצוב קלאסי ותחושת בית אמיתית.',
    'kitchens.formica': 'מטבחי פורמייקה',
    'kitchens.formica.en': 'Formica kitchens',
    'kitchens.wood': 'מטבחי עץ מלא',
    'kitchens.wood.en': 'Wood kitchens',
    'kitchens.nano': 'מטבחי נאנו',
    'kitchens.nano.en': 'Nano kitchens',
    'kitchens.nano.desc': 'מטבחי נאנו: המילה האחרונה בעיצוב המטבח – עמידות בפני שריטות וטביעות אצבע במראה מט יוקרתי.',
    'kitchens.acrylic': 'מטבחי אקריל',
    'kitchens.acrylic.en': 'Acrylic kitchens',

    // Testimonials
    'testimonials.title': 'לקוחות ממליצים',

    // Magazine
    'magazine.title': 'בלוג מטבחי Elite Design',
    'magazine.decorative': 'Blog',

    // Contact
    'contact.title': 'צרו קשר',
    'contact.name': 'שם מלא',
    'contact.phone': 'טלפון',
    'contact.email': 'אימייל',
    'contact.message': 'הודעה',
    'contact.send': 'שליחה',
    'contact.address': 'צה״ל 8, אשקלון',
    'contact.phone.number': '08-671-1767',

    // Footer
    'footer.rights': 'כל הזכויות שמורות',
    'footer.address': 'צה״ל 8, אשקלון',

    // Floating CTA
    'floating.customer': 'שירות ללקוח קיים',
    'floating.appointment': 'להזמין מעצב',

    // Pages
    'page.about.title': 'עלית דיזיין האומנות שבעיצוב החלל',

    'page.about.content': 'Elite Design — מעל 20 שנות ניסיון בתכנון וייצור מטבחים בהתאמה אישית בישראל. אנו מאמינים שהמטבח הוא לא רק רהיט, אלא לב הבית, שבו כל פרט קטן חשוב. אנו מתמחים בפתרונות יצירתיים: ממטבחי יוקרה בעיצוב מודרני עם ציפוי נאנו ועד לנגרות בהתאמה אישית וארונות מעוצבים. הייצור שלנו משלב טכנולוגיה מתקדמת ועבודת יד מוקפדת. אנו פועלים באזור המרכז והדרום: אשקלון, אשדוד ויישובים נוספים.',

    'page.showroom.title': 'אולם התצוגה שלנו',
    'page.showroom.desc': 'הזמנו אתכם לבקר באולם התצוגה שלנו ולחוות את המטבחים שלנו מקרוב',
    'page.projects.title': 'הפרויקטים שלנו',
    'page.installation.title': 'הכנה להתקנת מטבח',
    'page.promotions.title': 'מבצעים מיוחדים',
    'contact.success': 'ההודעה נשלחה בהצלחה!',
    'testimonials.header': 'מה הלקוחות שלנו אומרים',
    'testimonials.decorative': 'Client Testimonials',
    'testimonials.verified': 'Verified on Google',
    'quicknav.title': 'מה אנחנו עושים',
    'quicknav.item1.title': 'מטבחים בהתאמה אישית',
    'quicknav.item1.desc': 'תכנון וייצור אישי לכל חלל',
    'quicknav.item2.title': 'ארונות וחדרי ארונות',
    'quicknav.item2.desc': 'פתרונות אחסון מתקדמים בכל מידה',
    'quicknav.item3.title': 'נגרות בהתאמה אישית',
    'quicknav.item3.desc': 'ריהוט ופרטי עיצוב ייחודיים',
    'quicknav.item4.title': 'פרויקט מפתח',
    'quicknav.item4.desc': 'ליווי מלא משלב הרעיון ועד להתקנה',
    'featured.title': 'פרויקטים שבוצעו',
    'featured.decorative': 'Realized Projects',
    'featured.cta': 'לכל הפרויקטים',
    'featured.project1.city': 'ראשון לציון',
    'featured.project2.city': 'אשקלון',
    'featured.project3.city': 'קרית גת',
    'nav.closets': 'ארונות',
    'page.closets.title': 'ארונות בהתאמה אישית',
    'page.closets.decorative': 'Custom Closets & Wardrobes',
    'page.closets.hero.desc': 'אנו מייצרים ארונות בהתאמה אישית — ארונות הזזה, ארונות ציר ומערכות אחסון מובנות. אנו מעצבים רהיטים תוך התחשבות במבנה החדר, סגנון העיצוב והצרכים האישיים שלכם, ליצירת פתרונות פונקציונליים ואסתטיים לבית.',
    'closets.sliding.title': 'ארונות הזזה: מאפיינים, יתרונות וחסרונות',
    'closets.sliding.desc': 'ארון הזזה הוא ארון עצמאי או מובנה עם דלתות הנעות על מסילות. מבנה זה מאפשר ניצול יעיל של החלל ומתאים במיוחד לחדרים עם שטח מוגבל.',
    'closets.sliding.pros.title': 'יתרונות ארונות הזזה',
    'closets.sliding.pros.1': 'חיסכון במקום בזכות דלתות הזזה',
    'closets.sliding.pros.2': 'נוחות בשימוש יומיומי',
    'closets.sliding.pros.3': 'קיבולת גבוהה ואפשרות לאחסון חפצים גדולים',
    'closets.sliding.pros.4': 'מתאים למסדרונות, חדרי שינה וחדרים קטנים',
    'closets.sliding.cons.title': 'חסרונות ארונות הזזה',
    'closets.sliding.cons.1': 'התקנה מורכבת יותר בהשוואה לארונות ציר',
    'closets.sliding.cons.2': 'חלק מהנפח הפנימי נתפס על ידי מנגנון ההזזה',
    'closets.sliding.cons.3': 'ניתן לראות רק חלק אחד מהתכולה בכל פעם',

    // Installation Page
    'install.steps.title': 'רשימת הכנות לפני התקנה',
    'install.diagram.footer': 'המיקומים הם להמחשה בלבד. יש להיעזר בתוכנית המטבח האישית.',
    'install.checklist.title': 'רשימת ביקורת עצמית',
    'install.checklist.desc': 'סמנו כל שלב שביצעתם כדי לוודא שאתם מוכנים ב-100%',
    'install.checklist.complete': 'הושלם',
    'install.check.clear': 'פינוי מלא של המטבח הישן',
    'install.check.plumbing': 'נקודות מים וביוב לפי תוכנית',
    'install.check.electric': 'שקעים ונקודות חשמל במיקום הנכון',
    'install.check.walls': 'קירות צבועים וישרים (זווית 90)',
    'install.check.floor': 'ריצוף מושלם ופנלים מותקנים',
    'install.check.access': 'גישה חופשית למשאית וצוות',
    'install.point.hood': 'שקע לקולט אדים',
    'install.point.hood.desc': 'גובה מומלץ: 200-210 ס"מ מהרצפה',
    'install.point.counter': 'שקעי שירות',
    'install.point.counter.desc': 'מעל השיש, גובה 105 ס"מ',
    'install.point.dishwasher': 'הכנה למדיח',
    'install.point.dishwasher.desc': 'שקע, ברז וכניסת ביוב בארון כיור',
    'install.point.oven': 'שרשור לתנור',
    'install.point.oven.desc': 'שקע כוח נפרד לתנור וכיריים',
    'install.point.fridge': 'נקודה למקרר',
    'install.point.fridge.desc': 'ברז מים ושקע חשמל בגובה 220 ס"מ',
    'install.download.pdf': 'הורד סכמה (PDF)',
    'install.ask.expert': 'שאלה למתקין',

    // Image Comparison Slider
    'comparison.label.before': 'ציפייה',
    'comparison.label.after': 'הגשמת חלום',
    'comparison.btn.calc': 'אני רוצה גם! חישוב עלות',
    'comparison.title': 'שינוי עיצוב הפנים בקליק אחד',
    'comparison.subtitle': 'Interior transformation in one click',

    'closets.hinged.title': 'ארונות ציר: יתרונות וחסרונות',
    'closets.hinged.desc': 'ארונות ציר (פתיחה רגילה) הם הפתרון הקלאסי עם דלתות על צירים. הם מתאפיינים בפשטות מבנית ומתאים לעיצובים שבהם חשובים חזיתות ישרות ועומק אחסון מקסימלי.',
    'closets.hinged.pros.title': 'יתרונות ארונות ציר',
    'closets.hinged.pros.1': 'פתיחה שקטה וחלקה',
    'closets.hinged.pros.2': 'נפח אחסון פנימי מקסימלי',
    'closets.hinged.pros.3': 'החזיתות נמצאות במישור אחד',
    'closets.hinged.pros.4': 'מתאים לעיצובים מודרניים ומינימליסטיים',
    'closets.hinged.cons.title': 'חסרונות ארונות ציר',
    'closets.hinged.cons.1': 'נדרש שטח פנוי לפני הארון לפתיחת הדלתות',
    'closets.hinged.cons.2': 'אורך החיים תלוי באיכות הפרזול',
    'closets.care.title': 'תחזוקה ושימוש בארונות',
    'closets.care.desc': 'לעבודה תקינה של ארונות הזזה, מומלץ לנקות את המסילות מאבק מדי פעם. בארונות ציר חשוב לעקוב אחר מצב הצירים ולכוון אותם בעת הצורך. בטיפול נכון, שתי האפשרויות שומרות על פונקציונליות ומראה לאורך שנים רבות.',
    'closets.rooms.title': 'איך לבחור ארון לחדרים שונים',
    'closets.rooms.hallway.title': 'ארון למסדרון',
    'closets.rooms.hallway.desc': 'פתרונות חכמים לכניסה מרשימה וניצול שטח המסדרון.',
    'closets.rooms.bedroom.title': 'ארון לחדר שינה',
    'closets.rooms.bedroom.desc': 'ארונות מעוצבים ושקטים לאווירה רגועה ואחסון מקסימלי.',
    'closets.rooms.kids.title': 'ארון לחדר ילדים',
    'closets.rooms.kids.desc': 'עיצוב בטיחותי וצבעוני המותאם לצרכי הילדים.',
    'closets.rooms.living.title': 'ארון לסלון',
    'closets.rooms.living.desc': 'מערכות אחסון דקורטיביות המשתלבות בעיצוב הסלון.',
    'closets.custom.title': 'ייצור ארונות בהתאמה אישית',
    'closets.custom.desc': 'אנו מתכננים ומייצרים:',
    'closets.custom.list.1': 'ארונות הזזה בהתאמה אישית',
    'closets.custom.list.2': 'ארונות ציר',
    'closets.custom.list.3': 'ארונות מובנים',
    'closets.custom.list.4': 'מערכות אחסון אישיות',
    'closets.custom.footer': 'כל פרויקט נוצר לפי מידות אישיות עם בחירת חומרים, פרזול וחלוקה פנימית.',
    'closets.cta.title': 'צריכים ארון שמתאים בדיוק לעיצוב שלכם?',
    'closets.cta.desc': 'השאירו פרטים לייעוץ — אנו נעזור לכם לבחור את סוג הארון המתאים ביותר ונפתח פתרון שישתלב בצורה מושלמת בחלל שלכם.',
    'closets.seo.title': 'ארונות בהתאמה אישית, ארון הזזה, ארון ציר, ארון מובנה, רהיטים בהתאמה אישית, ארון למסדרון, ארון לחדר שינה, ארון לסלון.',

    'contact.error': 'לא ניתן לשלוח את ההודעה. אנא צור קשר ישירות.',
    'page.notfound.title': '404 - דף לא נמצא',
    'page.notfound.desc': 'אופס! הדף שחיפשת לא קיים.',
    'calc.title': 'חשב את עלות המטבח ב-5 צעדים',
    'calc.desc': 'הכניסו את הנתונים לחישוב ראשוני של עלות המטבח שלכם',
    'calc.type.label': 'סוג המטבח',
    'calc.type.straight': 'ישר',
    'calc.type.lshape': 'פינתי (ריש)',
    'calc.type.ushape': 'פינתי (ח)',
    'calc.type.island': 'מטבח עם אי',
    'calc.front.label': 'סוג החזית',
    'calc.front.formica': 'פורמייקה',
    'calc.front.polymer': 'פולימר',
    'calc.front.paint': 'צבע בתנור (שלייפלק)',
    'calc.front.acrylic': 'אקריל',
    'calc.front.wood': 'עץ מלא',
    'calc.counter.label': 'סוג שיש',
    'calc.counter.caes20': 'שיש קיסר 20 מ"מ',
    'calc.counter.caes40': 'שיש קיסר 40 מ"מ',
    'calc.counter.porcelain': 'גרניט פורצלן',
    'calc.counter.wood': 'עץ',
    'calc.hardware.label': 'סוג פרזול',
    'calc.hardware.standard': 'סטנדרטי',
    'calc.hardware.premium': 'פרומיום',
    'calc.hardware.super': 'סופר פרומיום',
    'calc.dimensions.label': 'מידות (ס"מ)',
    'calc.dimensions.len1': 'אורך 1',
    'calc.dimensions.len2': 'אורך 2',
    'calc.dimensions.len3': 'אורך 3',
    'calc.name': 'שם מלא',
    'calc.phone': 'טלפון',
    'calc.submit': 'קבל הצעת מחיר',
    'calc.success': 'הנתונים הוכנסו בהצלחה! ניצור איתך קשר בהקדם עם הצעת מחיר מדויקת.',
    'nav.calculator': 'חישוב עלות',
    'page.notfound.back': 'חזרה للدף הבית',
    'fitting.title': 'הדמיית עיצוב אינטראקטיבית',
    'fitting.subtitle': 'Interactive Design Fitting',
    'fitting.btn.white': 'לבן נאנו',
    'fitting.btn.graphite': 'גרפיט',
    'fitting.btn.oak': 'אלון',
    'fitting.btn.concrete': 'בטון',
    'fitting.btn.beige': 'בז\'',
    'fitting.white.title': 'לבן נאנו – מינימליזם טכנולוגי',
    'fitting.white.desc': 'משטח מט מושלם שאינו משאיר טביעות אצבע. המטבח שלכם תמיד נראה ללא רבב.',
    'fitting.graphite.title': 'אפור גרפיט – עומק וסטייל',
    'fitting.graphite.desc': 'גוון כהה ואצילי ליצירת ניגודיות אלגנטית. מעניק לחלל עוצמה אדריכלית.',
    'fitting.oak.title': 'אלון בהיר – חמימות טבעית',
    'fitting.oak.desc': 'טקסטורת עץ הממלאת את הבית בחמימות. פורניר עמיד עם דוגמה טבעית ייחודית.',
    'fitting.concrete.title': 'בטון כהה – לופט ואופי',
    'fitting.concrete.desc': 'פתרון טקסטורלי לחללים מודרניים. חומר פרקטי עם אסתטיקה תעשייתית ייחודית.',
    'fitting.beige.title': 'בז\' – הרמוניה רכה',
    'fitting.beige.desc': 'גוון רגוע וחם המרחיב ויזואלית את החלל ויוצר אווירת נעימות.',
    'whatsapp.tooltip': 'חישוב עלות ב-WhatsApp',
  },
  ru: {
    'about.cta.invite': 'Записаться на встречу (дизайнер)',
    'gallery.view': 'Смотреть',
    'about.process.desc': 'Ваш путь к идеальной кухне начинается здесь. Мы анализируем ваше пространство, учитываем привычки каждого члена семьи и превращаем сложные технические задачи в элегантные решения. В Elite Design мы не просто производим мебель — мы создаем комфорт, который вы будете чувствовать каждый день.',
    'about.years.suffix': ' лет+',
    'about.philosophy': '«Мы не просто ставим шкафы, мы создаем эргономику вашей жизни»',
    'seo.title': 'Elite Design | Кухни, шкафы и столярные изделия на заказ - 20 лет опыта',
    'seo.description': 'Столярная мастерская Elite Design специализируется на производстве кухонь и мебели более 20 лет. Шкафы, ванные комнаты и столярные решения для всего дома по доступным ценам и в отличном качестве. Обращайтесь за консультацией!',
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.kitchens': 'Кухни',
    'nav.kitchens.modern': 'Современные кухни',
    'nav.kitchens.country': 'Кухни в стиле кантри',
    'nav.kitchens.formica': 'Кухни из формайки',
    'nav.kitchens.wood': 'Кухни из массива',
    'nav.kitchens.nano': 'Нано кухни',
    'nav.kitchens.acrylic': 'Кухни из акрила',
    'nav.kitchens.styles': 'Стили',
    'nav.kitchens.projects': 'Проекты',
    'nav.kitchens.preparation': 'Подготовка',
    'nav.kitchens.quiz': 'Подбор кухни',
    'nav.projects': 'Проекты',
    'nav.promotions': 'Акции',
    'nav.installation': 'Подготовка к установке',
    'nav.magazine': 'Блог',
    'nav.showroom': 'Шоурум',
    'nav.contact': 'Контакты',
    'nav.quiz': 'Подбор кухни',

    // Hero
    'hero.title': 'Elite Design',
    'hero.subtitle': 'kitchens & more',
    'hero.tagline': 'Where Design Meets Quality',
    'hero.promo': 'Специальная скидка на все кухни',
    'hero.discount': 'Скидка 20%',
    'hero.cta.appointment': 'Записаться на встречу',
    'hero.cta.details': 'Оставить заявку',
    'hero.cta.calculator': 'Калькулятор стоимости',
    'hero.cta.main': 'Рассчитать ваш проект',

    // About Section
    'about.title': 'Дизайнерские кухни и столярные изделия по индивидуальному заказу',
    'about.decorative': 'Where Design Meets Quality',
    'about.description': 'Elite Design — это компания с более чем 20-летним опытом работы в сфере столярного дела. За эти годы мы построили тысячи кухонь и мебели для клиентов по всей стране. Наш секрет прост: мы любим свою работу. Опыт, накопленный нами за два десятилетия, позволяет нам предложить вам решение для любого бюджета и любых потребностей. Мы не верим в метод "конвейера" — у нас каждый клиент получает индивидуальный подход, точное планирование и полную поддержку до момента установки в доме.',
    'about.benefits.title': '',
    'about.benefits.1.title': 'Индивидуальный подход',

    'about.benefits.1.desc': 'Мы создаем проекты, которые идеально вписываются в ваш интерьер и ритм жизни.',

    'about.benefits.2.title': 'Материалы будущего',

    'about.benefits.2.desc': 'Работаем с инновационными покрытиями (Nano), формайка, акрил, натуральный шпон.',

    'about.benefits.3.title': 'Полный цикл',

    'about.benefits.3.desc': 'От профессионального замера и 3D-проектирования до безупречного монтажа.',

    'about.benefits.4.title': 'Качество без компромиссов',

    'about.benefits.4.desc': 'Используем лучшую фурнитуру мировых брендов (Blum, Hettich, Grass) для долговечности мебели.',


    'benefits.title': 'Почему стоит выбрать кухни Elite Design?',
    'whyus.title': 'Этапы нашей работы',
    'benefits.custom.title': 'Индивидуальный дизайн кухни',
    'benefits.custom.desc': 'Каждый проект — это уникальное произведение искусства, адаптированное к вашим потребностям и характеру.',
    'benefits.styles.title': 'Разнообразие стилей',
    'benefits.styles.desc': 'Современные кухни, кухни в стиле кантри, полимерные кухни и нано-кухни с использованием передовых технологий.',
    'benefits.quality.title': 'Бескомпромиссное качество',
    'benefits.quality.desc': 'Использование самой передовой фурнитуры в мире и долговечного сырья на долгие годы.',
    'benefits.local.title': 'Местное производство',
    'benefits.local.desc': 'Элитные столярные изделия израильского производства с строгим контролем каждой детали.',
    'whyus.decorative': 'working process',
    'process.step1.title': 'ЭСКИЗ И СТОИМОСТЬ',
    'process.step1.desc': 'Мы создадим эскиз и рассчитаем стоимость вашего проекта',
    'process.step2.title': 'ЗАМЕР',
    'process.step2.desc': 'Замерщик приедет в удобное для вас время',
    'process.step3.title': 'ИЗГОТОВЛЕНИЕ',
    'process.step3.desc': 'Изготовим ваш заказ на собственной фабрике',
    'process.step4.title': 'ДОСТАВКА И СБОРКА',
    'process.step4.desc': 'Доставим и соберём в вашей квартире',
    'process.step.label': 'шаг',
    'whyus.cta': 'Подробнее нажмите здесь',

    // Kitchen Categories
    'kitchens.title': 'Стили кухни',
    'kitchens.modern': 'Современные кухни',
    'kitchens.modern.en': 'Modern kitchens',
    'kitchens.modern.desc': 'Современные кухни: чистые линии, минималистичный вид и умные решения для хранения.',
    'kitchens.country': 'Кухни в стиле кантри',
    'kitchens.country.en': 'Country kitchens',
    'kitchens.country.desc': 'Кухни в стиле кантри: тепло натурального дерева, классический дизайн и ощущение настоящего дома.',
    'kitchens.formica': 'Кухни из формайки',
    'kitchens.formica.en': 'Formica kitchens',
    'kitchens.wood': 'Кухни из массива',
    'kitchens.wood.en': 'Wood kitchens',
    'kitchens.nano': 'Нано кухни',
    'kitchens.nano.en': 'Nano kitchens',
    'kitchens.nano.desc': 'Нано кухни: последнее слово в дизайне кухни – устойчивость к царапинам и отпечаткам пальцев с роскошным матовым видом.',
    'kitchens.acrylic': 'Кухни из акрила',
    'kitchens.acrylic.en': 'Acrylic kitchens',

    // Testimonials
    'testimonials.title': 'Отзывы клиентов',

    // Magazine
    'magazine.title': 'Блог Elite Design',
    'magazine.decorative': 'Blog',

    // Contact
    'contact.title': 'Свяжитесь с нами',
    'contact.name': 'Полное имя',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить',
    'contact.address': 'Цахаль 8, Ашкелон',
    'contact.phone.number': '08-671-1767',

    // Footer
    'footer.rights': 'Все права защищены',
    'footer.address': 'Цахаль 8, Ашкелон',

    // Floating CTA
    'floating.customer': 'Обслуживание клиентов',
    'floating.appointment': 'Пригласить дизайнера',

    // Pages
    'page.about.title': 'Elite Design Искусство создания пространства',

    'page.about.content': 'Elite Design — это более 20 лет опыта в проектировании и производстве кухонь на заказ в Израиле. Мы верим, что кухня — это не просто мебель, а сердце дома, где важна каждая деталь. Мы специализируемся на индивидуальных решениях: от современных дизайнерских кухонь с покрытием Nano до эксклюзивных столярных изделий и шкафов. Наше производство объединяет передовые технологии и мастерство ручной работы. Мы работаем в центре и на юге страны: Ашкелон, Ашдод и другие города.',

    'page.showroom.title': 'Наш шоурум',
    'page.showroom.desc': 'Приглашаем вас посетить наш шоурум и лично оценить качество наших кухонь',
    'page.projects.title': 'Наши проекты',
    'page.installation.title': 'Подготовка к установке кухни',
    'page.promotions.title': 'Специальные акции',
    'contact.success': 'Сообщение успешно отправлено!',
    'testimonials.header': 'Что говорят о нас в домах Израиля',
    'testimonials.decorative': 'Client Testimonials',
    'testimonials.verified': 'Verified on Google',
    'quicknav.title': 'Что мы делаем',
    'quicknav.item1.title': 'Кухни на заказ',
    'quicknav.item1.desc': 'Индивидуальный дизайн и производство',
    'quicknav.item2.title': 'Шкафы и гардеробные',
    'quicknav.item2.desc': 'Встроенные решения под размер',
    'quicknav.item3.title': 'Индивидуальная столярка',
    'quicknav.item3.desc': 'Мебель и элементы под проект',
    'quicknav.item4.title': 'Проект под ключ',
    'quicknav.item4.desc': 'От идеи до установки',
    'featured.title': 'Реализованные проекты',
    'featured.decorative': 'Realized Projects',
    'featured.cta': 'Смотреть все проекты',
    'featured.project1.city': 'Ришон ле-Цион',
    'featured.project2.city': 'Ашкелон',
    'featured.project3.city': 'Кирьят Гат',
    'nav.closets': 'Шкафы',
    'page.closets.title': 'Шкафы на заказ',
    'page.closets.decorative': 'Custom Closets & Wardrobes',
    'page.closets.hero.desc': 'Мы изготавливаем шкафы на заказ — шкафы-купе, распашные и встроенные системы хранения. Проектируем мебель с учётом планировки, стиля интерьера и индивидуальных потребностей, создавая функциональные и эстетичные решения для дома.',
    'closets.sliding.title': 'Шкафы-купе: особенности, преимущества и недостатки',
    'closets.sliding.desc': 'Шкаф-купе — это отдельно стоящий или встроенный шкаф с раздвижными дверями, которые движутся по направляющим. Такая конструкция позволяет эффективно использовать пространство и подходит для помещений с ограниченной площадью.',
    'closets.sliding.pros.title': 'Преимущества шкафов-купе',
    'closets.sliding.pros.1': 'экономия пространства за счёт раздвижных дверей',
    'closets.sliding.pros.2': 'удобство ежедневного использования',
    'closets.sliding.pros.3': 'высокая вместительность и возможность хранения габаритных вещей',
    'closets.sliding.pros.4': 'подходит для прихожих, спален и небольших комнат',
    'closets.sliding.cons.title': 'Недостатки шкафов-купе',
    'closets.sliding.cons.1': 'более сложный монтаж по сравнению с распашными моделями',
    'closets.sliding.cons.2': 'часть внутреннего объёма занимает раздвижной механизм',
    'closets.sliding.cons.3': 'одновременно видна только одна часть содержимого',
    'closets.hinged.title': 'Распашные шкафы: плюсы и минусы',
    'closets.hinged.desc': 'Распашные шкафы — классическое решение с дверцами на петлях. Они отличаются простотой конструкции и подходят для интерьеров, где важны ровные фасады и максимальная глубина хранения.',
    'closets.hinged.pros.title': 'Преимущества распашных шкафов',
    'closets.hinged.pros.1': 'бесшумное и плавное открывание',
    'closets.hinged.pros.2': 'максимальный полезный внутренний объём',
    'closets.hinged.pros.3': 'фасады находятся в одной плоскости',
    'closets.hinged.pros.4': 'подходят для современных и минималистичных интерьеров',

    // Installation Page
    'install.steps.title': 'Подготовка к установке',
    'install.diagram.footer': 'Расположение указано для примера. Следуйте вашему персональному плану.',
    'install.checklist.title': 'Чек-лист готовности',
    'install.checklist.desc': 'Отмечайте выполненные пункты, чтобы быть уверенными на 100%',
    'install.checklist.complete': 'Готово',
    'install.check.clear': 'Полный демонтаж старой кухни',
    'install.check.plumbing': 'Точки воды и слива по плану',
    'install.check.electric': 'Розетки и выводы электричества',
    'install.check.walls': 'Стены покрашены и выровнены (угол 90)',
    'install.check.floor': 'Пол готов, плинтуса установлены',
    'install.check.access': 'Свободный доступ для бригады',
    'install.point.hood': 'Розетка для вытяжки',
    'install.point.hood.desc': 'Реком. высота: 200-210 см',
    'install.point.counter': 'Рабочие розетки',
    'install.point.counter.desc': 'Над столешницей, высота 105 см',
    'install.point.dishwasher': 'Посудомойка',
    'install.point.dishwasher.desc': 'Розетка, кран и слив в шкафу мойки',
    'install.point.oven': 'Духовой шкаф',
    'install.point.oven.desc': 'Отдельная силовая розетка',
    'install.point.fridge': 'Холодильник',
    'install.point.fridge.desc': 'Розетка и кран воды на высоте 220 см',
    'install.download.pdf': 'Скачать схему (PDF)',
    'install.ask.expert': 'Вопрос мастеру',

    // Image Comparison Slider
    'comparison.label.before': 'Ожидание',
    'comparison.label.after': 'Воплощение мечты',
    'comparison.btn.calc': 'Хочу так же! Рассчитать стоимость',
    'comparison.title': 'Трансформация интерьера в один клик',
    'comparison.subtitle': 'Interior transformation in one click',


    'closets.hinged.cons.title': 'Недостатки распашных шкафов',
    'closets.hinged.cons.1': 'требуется свободное пространство перед шкафом',
    'closets.hinged.cons.2': 'срок службы зависит от качества фурнитуры',
    'closets.care.title': 'Уход и эксплуатация шкафов',
    'closets.care.desc': 'Для корректной работы шкафов-купе рекомендуется периодически очищать направляющие от пыли. В распашных шкафах важно следить за состоянием петель и при необходимости регулировать их. При правильном уходе оба варианта сохраняют функциональность и внешний вид на протяжении многих лет.',
    'closets.rooms.title': 'Как выбрать шкаф для разных помещений',
    'closets.rooms.hallway.title': 'Шкаф в прихожую',
    'closets.rooms.hallway.desc': 'Умные решения для прихожей и эффективного использования коридора.',
    'closets.rooms.bedroom.title': 'Шкаф в спальню',
    'closets.rooms.bedroom.desc': 'Стильные и бесшумные шкафы для максимального комфорта в спальне.',
    'closets.rooms.kids.title': 'Шкаф в детскую',
    'closets.rooms.kids.desc': 'Безопасный и яркий дизайн, адаптированный для нужд детей.',
    'closets.rooms.living.title': 'Шкаф в гостиную',
    'closets.rooms.living.desc': 'Декоративные системы хранения, идеально дополняющие интерьер гостиной.',
    'closets.custom.title': 'Изготовление шкафов на заказ',
    'closets.custom.desc': 'Мы разрабатываем и изготавливаем:',
    'closets.custom.list.1': 'шкафы-купе на заказ',
    'closets.custom.list.2': 'распашные шкафы',
    'closets.custom.list.3': 'встроенные шкафы',
    'closets.custom.list.4': 'индивидуальные системы хранения',
    'closets.custom.footer': 'Каждый проект создаётся по индивидуальным размерам с подбором материалов, фурнитуры и внутреннего наполнения.',
    'closets.cta.title': 'Нужен шкаф под ваш интерьер?',
    'closets.cta.desc': 'Оставьте заявку на консультацию — мы поможем подобрать оптимальный тип шкафа и разработаем решение, которое идеально впишется в ваше пространство.',
    'closets.seo.title': 'Шкафы на заказ, шкаф-купе, распашной шкаф, встроенный шкаф, мебель на заказ, шкаф в прихожую, шкаф в спальню, шкаф в гостиную.',

    'contact.error': 'Не удалось отправить сообщение. Пожалуйста, свяжитесь с нами напрямую.',
    'page.notfound.title': '404 - Страница не найдена',
    'page.notfound.desc': 'Ой! Страница, которую вы ищете, не существует.',
    'calc.title': 'Рассчитайте стоимость кухни за 5 шагов',
    'calc.desc': 'Введите данные для предварительного расчета стоимости вашей кухни',
    'calc.type.label': 'Тип кухни',
    'calc.type.straight': 'Прямая',
    'calc.type.lshape': 'Угловая (L)',
    'calc.type.ushape': 'П-образная',
    'calc.type.island': 'Кухня с островом',
    'calc.front.label': 'Тип фасада',
    'calc.front.formica': 'Формайка',
    'calc.front.polymer': 'Полимер',
    'calc.front.paint': 'Покраска (Lacquered)',
    'calc.front.acrylic': 'Акрил',
    'calc.front.wood': 'Массив дерева',
    'calc.counter.label': 'Тип столешницы',
    'calc.counter.caes20': 'Caesarstone 20мм',
    'calc.counter.caes40': 'Caesarstone 40мм',
    'calc.counter.porcelain': 'Керамогранит',
    'calc.counter.wood': 'Дерево',
    'calc.hardware.label': 'Тип фурнитуры',
    'calc.hardware.standard': 'Стандарт',
    'calc.hardware.premium': 'Премиум',
    'calc.hardware.super': 'Супер Премиум',
    'calc.dimensions.label': 'Размеры (см)',
    'calc.dimensions.len1': 'Длина 1',
    'calc.dimensions.len2': 'Длина 2',
    'calc.dimensions.len3': 'Длина 3',
    'calc.name': 'Имя',
    'calc.phone': 'Телефон',
    'calc.submit': 'Получить расчет',
    'calc.success': 'Данные успешно отправлены! Мы свяжемся с вами в ближайшее время с точным расчетом.',
    'nav.calculator': 'Калькулятор',
    'page.notfound.back': 'Вернуться на главную',
    'fitting.title': 'Интерактивная примерка дизайна',
    'fitting.subtitle': 'Interactive Design Fitting',
    'fitting.btn.white': 'Белый Nano',
    'fitting.btn.graphite': 'Графит',
    'fitting.btn.oak': 'Дуб',
    'fitting.btn.concrete': 'Бетон',
    'fitting.btn.beige': 'Беж',
    'fitting.white.title': 'Белый Nano – Технологичный минимализм',
    'fitting.white.desc': 'Идеально матовая поверхность, на которой не остаются отпечатки пальцев. Ваша кухня всегда выглядит безупречно.',
    'fitting.graphite.title': 'Серый графит – Глубина и стиль',
    'fitting.graphite.desc': 'Благородный темный оттенок для создания элегантного контраста. Придает интерьеру архитектурную строгость.',
    'fitting.oak.title': 'Светлый дуб – Натуральный уют',
    'fitting.oak.desc': 'Текстура дерева наполняет дом теплом. Износостойкий шпон с неповторимым природным рисунком.',
    'fitting.concrete.title': 'Темный бетон – Лофт и характер',
    'fitting.concrete.desc': 'Фактурное решение для современных пространств. Практичный материал с уникальной индустриальной эстетикой.',
    'fitting.beige.title': 'Беж – Мягкая гармония',
    'fitting.beige.desc': 'Спокойный, теплый тон, который визуально расширяет пространство и создает атмосферу уюта.',
    'whatsapp.tooltip': 'Рассчитать стоимость в WhatsApp',
  },
  en: {
    'about.cta.invite': 'Invite Designer for Measurement',
    'gallery.view': 'View',
    'about.process.desc': 'Your journey to the perfect kitchen starts here. We analyze your space, consider every family members habits, and turn complex technical tasks into elegant solutions. At Elite Design, we don’t just make furniture—we create the comfort you’ll feel every day.',
    'about.years.suffix': '+ Years',
    'about.philosophy': '“We don’t just install cabinets, we design the ergonomics of your life”',
    'seo.title': 'Elite Design | Custom Kitchens, Closets & Woodworking - 20 Years Experience',
    'seo.description': 'Elite Design Carpentry specializes in manufacturing kitchens and furniture for over 20 years. Closets, bathrooms, and woodworking solutions for the whole home at affordable prices and excellent quality. Contact us for a consultation!',
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.kitchens': 'Kitchens',
    'nav.kitchens.modern': 'Modern Kitchens',
    'nav.kitchens.country': 'Country Kitchens',
    'nav.kitchens.formica': 'Formica Kitchens',
    'nav.kitchens.wood': 'Solid Wood Kitchens',
    'nav.kitchens.nano': 'Nano Kitchens',
    'nav.kitchens.acrylic': 'Acrylic Kitchens',
    'nav.kitchens.styles': 'Styles',
    'nav.kitchens.projects': 'Projects',
    'nav.kitchens.preparation': 'Preparation',
    'nav.kitchens.quiz': 'Kitchen Selector',
    'nav.projects': 'Projects',
    'nav.promotions': 'Promotions',
    'nav.installation': 'Preparation for Installation',
    'nav.magazine': 'Blog',
    'nav.showroom': 'Showroom',
    'nav.contact': 'Contact Us',
    'nav.quiz': 'Kitchen Selector',

    // Hero
    'hero.title': 'Elite Design',
    'hero.subtitle': 'kitchens & more',
    'hero.tagline': 'Where Design Meets Quality',
    'hero.promo': 'Special discount on all kitchens',
    'hero.discount': '20% OFF',
    'hero.cta.appointment': 'Book an Appointment',
    'hero.cta.details': 'Leave Details',
    'hero.cta.calculator': 'Cost Calculator',
    'hero.cta.main': 'Calculate Your Project',

    // About Section
    'about.title': 'Designer Kitchens & Custom Cabinetry',
    'about.decorative': 'Where Design Meets Quality',
    'about.description': 'Elite Design is a company with over 20 years of experience in the carpentry field. Over the years, we have built thousands of kitchens and furniture for customers all over the country. Our secret is simple: we love our work. The experience we have gained over two decades allows us to provide you with a solution for every budget and every need. We do not believe in the "conveyor belt system" – with us, every customer receives personal attention, precise planning, and full support until the furniture is installed in the home.',
    'about.benefits.title': '',
    'about.benefits.1.title': 'Individual Approach',

    'about.benefits.1.desc': 'We create projects that fit perfectly into your interior and lifestyle.',

    'about.benefits.2.title': 'Future Materials',

    'about.benefits.2.desc': 'Working with innovative coatings (Nano), Formica, Acrylic, and natural Veneer.',

    'about.benefits.3.title': 'Full Cycle',

    'about.benefits.3.desc': 'From professional measurement and 3D design to flawless installation.',

    'about.benefits.4.title': 'Uncompromising Quality',

    'about.benefits.4.desc': 'Using the worlds best hardware (Blum, Hettich, Grass) for your furnitures longevity.',


    'benefits.title': 'Why Choose Elite Design Kitchens?',
    'whyus.title': 'Stages of our work',
    'benefits.custom.title': 'Custom Kitchen Design',
    'benefits.custom.desc': 'Every project is a unique work of art tailored to your needs and personality.',
    'benefits.styles.title': 'Variety of Styles',
    'benefits.styles.desc': 'Modern kitchens, country kitchens, polymer kitchens, and nano-kitchens using advanced technology.',
    'benefits.quality.title': 'Uncompromising Quality',
    'benefits.quality.desc': "Using the world's most advanced hardware and durable materials for years to come.",
    'benefits.local.title': 'Local Production',
    'benefits.local.desc': 'Elite "Blue and White" cabinetry with strict control over every single detail.',
    'whyus.decorative': 'working process',
    'process.step1.title': 'SKETCH & ESTIMATE',
    'process.step1.desc': 'We will create a preliminary sketch and calculate the cost for you',
    'process.step2.title': 'MEASUREMENT',
    'process.step2.desc': 'Our professional measurer will visit at your convenience',
    'process.step3.title': 'PRODUCTION',
    'process.step3.desc': 'We manufacture your kitchen in our own factory with cutting-edge technology',
    'process.step4.title': 'DELIVERY & ASSEMBLY',
    'process.step4.desc': 'We transport and professionally install the kitchen in your home',
    'process.step.label': 'step',
    'whyus.cta': 'Click here for more details',

    // Kitchen Categories
    'kitchens.title': 'Kitchen Styles',
    'kitchens.modern': 'Modern Kitchens',
    'kitchens.modern.en': 'Modern Kitchens',
    'kitchens.modern.desc': 'Modern Kitchens: Clean lines, minimalist look, and smart storage solutions.',
    'kitchens.country': 'Country Kitchens',
    'kitchens.country.en': 'Country Kitchens',
    'kitchens.country.desc': 'Country Kitchens: Warmth of natural wood, classic design, and a true feeling of home.',
    'kitchens.formica': 'Formica Kitchens',
    'kitchens.formica.en': 'Formica Kitchens',
    'kitchens.wood': 'Solid Wood Kitchens',
    'kitchens.wood.en': 'Solid Wood Kitchens',
    'kitchens.nano': 'Nano Kitchens',
    'kitchens.nano.en': 'Nano Kitchens',
    'kitchens.nano.desc': 'Nano Kitchens: The last word in kitchen design – resistance to scratches and fingerprints with a luxury matte look.',
    'kitchens.acrylic': 'Acrylic Kitchens',
    'kitchens.acrylic.en': 'Acrylic Kitchens',

    // Testimonials
    'testimonials.title': 'Client Testimonials',

    // Magazine
    'magazine.title': 'Elite Design Blog',
    'magazine.decorative': 'Blog',

    // Contact
    'contact.title': 'Contact Us',
    'contact.name': 'Full Name',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send',
    'contact.address': '8 Zahal St, Ashkelon',
    'contact.phone.number': '08-671-1767',

    // Footer
    'footer.rights': 'All rights reserved',
    'footer.address': '8 Zahal St, Ashkelon',

    // Floating CTA
    'floating.customer': 'Customer Service',
    'floating.appointment': 'Invite Designer',

    // Pages
    'page.about.title': 'Elite Design The Art of Space Creation',

    'page.about.content': 'Elite Design brings over 20 years of experience in custom kitchen design and production in Israel. We believe a kitchen is more than just furniture—it’s the heart of the home, where every detail matters. We specialize in bespoke solutions: from modern designer kitchens with Nano coating to exclusive carpentry and closets. Our production combines cutting-edge technology with handcrafted mastery. Serving the Central and Southern regions, including Ashkelon, Ashdod, and surrounding areas.',

    'page.showroom.title': 'Our Showroom',
    'page.showroom.desc': 'We invite you to visit our showroom and experience our kitchens up close',
    'page.projects.title': 'Our Projects',
    'page.installation.title': 'Preparation for Kitchen Installation',
    'page.promotions.title': 'Special Promotions',
    'contact.success': 'Message sent successfully!',
    'testimonials.header': 'What people say in Israel homes',
    'testimonials.decorative': 'Client Testimonials',
    'testimonials.verified': 'Verified on Google',
    'quicknav.title': 'What we do',
    'quicknav.item1.title': 'Custom Kitchens',
    'quicknav.item1.desc': 'Individual design & manufacturing',
    'quicknav.item2.title': 'Closets & Wardrobes',
    'quicknav.item2.desc': 'Built-in solutions for any size',
    'quicknav.item3.title': 'Custom Woodworking',
    'quicknav.item3.desc': 'Furniture & elements per project',
    'quicknav.item4.title': 'Turnkey Projects',
    'quicknav.item4.desc': 'From concept to installation',
    'featured.title': 'Realized Projects',
    'featured.decorative': 'Realized Projects',
    'featured.cta': 'See all projects',
    'featured.project1.city': 'Rishon LeZion',
    'featured.project2.city': 'Ashkelon',
    'featured.project3.city': 'Kiryat Gat',
    'nav.closets': 'Closets',
    'page.closets.title': 'Custom Closets',
    'page.closets.decorative': 'Custom Closets & Wardrobes',
    'page.closets.hero.desc': 'We manufacture custom wardrobes — sliding, hinged, and built-in storage systems. We design furniture taking into account the layout, interior style, and individual needs, creating functional and aesthetic solutions for the home.',
    'closets.sliding.title': 'Sliding Closets: Features, Advantages, and Disadvantages',
    'closets.sliding.desc': 'A sliding wardrobe is a free-standing or built-in closet with sliding doors that move along tracks. This design allows for efficient use of space and is suitable for rooms with limited area.',
    'closets.sliding.pros.title': 'Advantages of Sliding Closets',
    'closets.sliding.pros.1': 'space saving due to sliding doors',
    'closets.sliding.pros.2': 'convenience of daily use',
    'closets.sliding.pros.3': 'high capacity and possibility of storing bulky items',
    'closets.sliding.pros.4': 'suitable for hallways, bedrooms, and small rooms',
    'closets.sliding.cons.title': 'Disadvantages of Sliding Closets',
    'closets.sliding.cons.1': 'more complex installation compared to hinged models',
    'closets.sliding.cons.2': 'part of the internal volume is occupied by the sliding mechanism',
    'closets.sliding.cons.3': 'only one part of the contents is visible at a time',
    'closets.hinged.title': 'Hinged Closets: Pros and Cons',
    'closets.hinged.desc': 'Hinged wardrobes are a classic solution with doors on hinges. They are characterized by simplicity of design and are suitable for interiors where smooth facades and maximum storage depth are important.',
    'closets.hinged.pros.title': 'Advantages of Hinged Closets',
    'closets.hinged.pros.1': 'quiet and smooth opening',
    'closets.hinged.pros.2': 'maximum useful internal volume',
    'closets.hinged.pros.3': 'facades are in the same plane',

    // Installation Page
    'install.steps.title': 'Preparation Checklist',
    'install.diagram.footer': 'Locations are for illustration only. Refer to your personal kitchen plan.',
    'install.checklist.title': 'Self-Check List',
    'install.checklist.desc': 'Check off each completed step to ensure 100% readiness',
    'install.checklist.complete': 'Complete',
    'install.check.clear': 'Complete removal of old kitchen',
    'install.check.plumbing': 'Water and sewage points per plan',
    'install.check.electric': 'Sockets and electrical points correctly placed',
    'install.check.walls': 'Walls painted and straight (90 degree angles)',
    'install.check.floor': 'Flooring complete and skirting installed',
    'install.check.access': 'Clear access for truck and team',
    'install.point.hood': 'Hood Socket',
    'install.point.hood.desc': 'Rec. height: 200-210 cm',
    'install.point.counter': 'Service Sockets',
    'install.point.counter.desc': 'Above counter, height 105 cm',
    'install.point.dishwasher': 'Dishwasher Prep',
    'install.point.dishwasher.desc': 'Socket, tap, and drain in sink cabinet',
    'install.point.oven': 'Oven Power',
    'install.point.oven.desc': 'Separate power socket for oven/hob',
    'install.point.fridge': 'Refrigerator',
    'install.point.fridge.desc': 'Water tap and socket at 220 cm',
    'install.download.pdf': 'Download Plan (PDF)',
    'install.ask.expert': 'Ask Expert',

    // Image Comparison Slider
    'comparison.label.before': 'Expectation',
    'comparison.label.after': 'Dream Realized',
    'comparison.btn.calc': 'I want this too! Calculate Cost',
    'comparison.title': 'Interior Transformation in One Click',
    'comparison.subtitle': 'Interior transformation in one click',

    'closets.hinged.pros.4': 'suitable for modern and minimalist interiors',
    'closets.hinged.cons.title': 'Disadvantages of Hinged Closets',
    'closets.hinged.cons.1': 'free space is required in front of the closet',
    'closets.hinged.cons.2': 'service life depends on the quality of the hardware',
    'closets.care.title': 'Maintenance and Operation',
    'closets.care.desc': 'For correct operation of sliding wardrobes, it is recommended to periodically clean the tracks from dust. In hinged wardrobes, it is important to monitor the state of the hinges and adjust them if necessary. With proper care, both options maintain functionality and appearance for many years.',
    'closets.rooms.title': 'How to Choose a Closet for Different Rooms',
    'closets.rooms.hallway.title': 'Hallway Closet',
    'closets.rooms.hallway.desc': 'Smart storage solutions for a welcoming and efficient entryway.',
    'closets.rooms.bedroom.title': 'Bedroom Closet',
    'closets.rooms.bedroom.desc': 'Elegant, quiet wardrobes for maximum comfort and storage.',
    'closets.rooms.kids.title': 'Kids Room Closet',
    'closets.rooms.kids.desc': 'Safe and colorful designs tailored specifically for children.',
    'closets.rooms.living.title': 'Living Room Closet',
    'closets.rooms.living.desc': 'Decorative storage systems that blend seamlessly with your living room.',
    'closets.custom.title': 'Custom Closet Production',
    'closets.custom.desc': 'We develop and manufacture:',
    'closets.custom.list.1': 'custom sliding wardrobes',
    'closets.custom.list.2': 'hinged wardrobes',
    'closets.custom.list.3': 'built-in wardrobes',
    'closets.custom.list.4': 'individual storage systems',
    'closets.custom.footer': 'Each project is created according to individual dimensions with the selection of materials, hardware, and internal filling.',
    'closets.cta.title': 'Need a closet for your interior?',
    'closets.cta.desc': 'Leave a request for a consultation — we will help you choose the optimal type of closet and develop a solution that fits perfectly into your space.',
    'closets.seo.title': 'Custom closets, sliding wardrobe, hinged closet, built-in closet, custom furniture, hallway closet, bedroom closet, living room closet.',

    'contact.error': 'Could not send message. Please contact us directly.',
    'page.notfound.title': '404 - Page Not Found',
    'page.notfound.desc': "Oops! The page you are looking for doesn't exist.",
    'calc.title': 'Calculate Kitchen Cost in 5 Steps',
    'calc.desc': 'Enter the data for an initial calculation of your kitchen cost',
    'calc.type.label': 'Kitchen Type',
    'calc.type.straight': 'Straight',
    'calc.type.lshape': 'L-Shape',
    'calc.type.ushape': 'U-Shape',
    'calc.type.island': 'With Island',
    'calc.front.label': 'Front Material',
    'calc.front.formica': 'Formica',
    'calc.front.polymer': 'Polymer',
    'calc.front.paint': 'Painted (Lacquered)',
    'calc.front.acrylic': 'Acrylic',
    'calc.front.wood': 'Solid Wood',
    'calc.counter.label': 'Countertop Type',
    'calc.counter.caes20': 'Caesarstone 20mm',
    'calc.counter.caes40': 'Caesarstone 40mm',
    'calc.counter.porcelain': 'Porcelain',
    'calc.counter.wood': 'Wood',
    'calc.hardware.label': 'Hardware Type',
    'calc.hardware.standard': 'Standard',
    'calc.hardware.premium': 'Premium',
    'calc.hardware.super': 'Super Premium',
    'calc.dimensions.label': 'Dimensions (cm)',
    'calc.dimensions.len1': 'Length 1',
    'calc.dimensions.len2': 'Length 2',
    'calc.dimensions.len3': 'Length 3',
    'calc.name': 'Full Name',
    'calc.phone': 'Phone Number',
    'calc.submit': 'Get Quote',
    'calc.success': 'Data submitted successfully! We will contact you shortly with an accurate quote.',
    'nav.calculator': 'Cost Calculator',
    'page.notfound.back': 'Return Home',
    'fitting.title': 'Interactive Design Fitting',
    'fitting.subtitle': 'Interactive Design Fitting',
    'fitting.btn.white': 'White Nano',
    'fitting.btn.graphite': 'Graphite',
    'fitting.btn.oak': 'Oak',
    'fitting.btn.concrete': 'Concrete',
    'fitting.btn.beige': 'Beige',
    'fitting.white.title': 'White Nano – Technological Minimalism',
    'fitting.white.desc': 'Perfectly matte surface that leaves no fingerprints. Your kitchen always looks flawless.',
    'fitting.graphite.title': 'Graphite Gray – Depth and Style',
    'fitting.graphite.desc': 'A noble dark shade to create an elegant contrast. Gives the interior architectural rigor.',
    'fitting.oak.title': 'Light Oak – Natural Comfort',
    'fitting.oak.desc': 'The texture of wood fills the home with warmth. Wear-resistant veneer with a unique natural pattern.',
    'fitting.concrete.title': 'Dark Concrete – Loft and Character',
    'fitting.concrete.desc': 'A textured solution for modern spaces. Practical material with a unique industrial aesthetic.',
    'fitting.beige.title': 'Beige – Soft Harmony',
    'fitting.beige.desc': 'A calm, warm tone that visually expands the space and creates an atmosphere of coziness.',
    'whatsapp.tooltip': 'Calculate cost in WhatsApp',
  },
};

const FALLBACK_LANGUAGE: Language = 'he';
const SUPPORTED_LANGUAGES: Language[] = ['he', 'ru', 'en'];

const getInitialLanguage = (): Language => {
  if (typeof window === 'undefined') return FALLBACK_LANGUAGE;

  // Check localStorage for user's manual language choice
  try {
    const saved = localStorage.getItem('language') as Language;
    if (saved && SUPPORTED_LANGUAGES.includes(saved)) {
      return saved;
    }
  } catch (e) {
    console.error('Error reading from localStorage', e);
  }

  // Default to Hebrew
  return FALLBACK_LANGUAGE;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const dir = language === 'he' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('language', lang);
    } catch (e) {
      console.error('Error saving to localStorage', e);
    }
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    return translation !== undefined ? translation : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
